### ISSUE TITLE
Output Data Format

### ISSUE THREAD

**Issue by bitner** [developmentseed/openaq-etl#1]
The data model for the target database for this process has two main parts - metadata about the station/sensors which does not change often and is generally changed with updates when it does change and insert only records for individual measurements.

The metadata is normalized in it's final storage, but transfer could be done in a flattened form. 

Notes for the individual tables can be found at https://docs.google.com/spreadsheets/d/1mvKclBguYo5CsFvTIG5FiId5Sr2XMxVWs8IxhtTc6qI/edit?ts=5f888e74#gid=1301608214

Visual chart of the data model:
![datamodel](https://user-images.githubusercontent.com/164828/97906094-b6474500-1d08-11eb-8bd4-0165359fd232.png)

The biggest key to the normalization is that we need an identifier for each individual sensor (a location can have multiple sensors for each thing being measured). Ideally measurements data will come through with *only* the following fields:
sensor_id, timestamp, value (for stationary data)
and 
sensor_id, timestamp, value, lat, lon (for mobile data)

All other data will end up getting normalized out into separate tables, but could come in as flattened csv, or nested json

**Comment by bitner** [comment]
Ultimate format for the metadata needs to provide for a structure like this, that being said, as long as I get all the information here, I can deal with just about anything on the database ingest side.
{
    "<sourceid>": {
        "sensor_nodes":
    [
        {
            "sensor_node_site_name" : ... # name provided by the source that is unique within a source,
            "sensor_node_geometry": {"latitude": ..., "longitude": ...}, # not needed if mobile
            "sensor_node_is_mobile": ...,
            ... any other field that can be mapped to something in the sensor node tab on https://docs.google.com/spreadsheets/d/1mvKclBguYo5CsFvTIG5FiId5Sr2XMxVWs8IxhtTc6qI/edit?ts=5f888e74#gid=1132575684
            "sensor_systems": [ # for most sources there will be just one sensor system
                {
                    "sensor_system_name": ... # name provided by the source unique within a node -- if there is only one this can be blank,
                    ... any field from that can be mapped to something in the sensor system tab on the spreadsheet,
                    "sensors" : [
                        {
                            "measurand" : ...,
                            "units": ....
                            ... any field that can be mapped to something from the sensor tab on the spreadsheet
                            ### alternate option to the two
                        }
                    ]
                }
            ]
        }
    ]
}

We could break down using directories as well where the sources directory contained a directory for each sensor node which had a sensor_node.json and a directory for each sensor system etc

**Comment by ingalls** [comment]
Going to close this issue as in our previous discussion we were mostly in line with the desired format. Let's open new issues for specific actionable items now that we have the general format implemented.
